### ISSUE TITLE
Lack of checking for Null?

### ISSUE THREAD

**Issue by Bugcheckers** [Monetra/mstdlib#3]
I have seen in the code that event variable is usually checked before calling M_event_lock(event)

Like:
https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L977
https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L1020
https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L1080
https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L1100
...

Except here:

https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L940

Can you please evaluate it?

Thanks!

**Comment by bradh352** [comment]
That function is a static callback, which is only called from here:

https://github.com/Monetra/mstdlib/blob/master/io/m_event.c#L991

Which then gets executed here:
https://github.com/Monetra/mstdlib/blob/master/io/m_event_timer.c#L525

Since an event loop always passes its own event handle to a callback, its not possible for the event handle to be NULL.
